/* xrt 模块闭包：xjwt 需要的 xrt 核心能力。 */
#ifndef XJWT_XRT_H
#define XJWT_XRT_H

#define XRT_MODULE_JSON_READ
#define XRT_MODULE_JSON_WRITE
#define XRT_MODULE_VALUE
#define XRT_MODULE_CODEC_BASE64
#define XRT_MODULE_CRYPTO_CORE
#define XRT_MODULE_CRYPTO_SHA256
#define XRT_MODULE_CRYPTO_SHA384
#define XRT_MODULE_CRYPTO_SHA512
#define XRT_MODULE_CRYPTO_HMAC_SHA256
#define XRT_MODULE_CRYPTO_HMAC_SHA384
#define XRT_MODULE_CRYPTO_HMAC_SHA512
#define XRT_MODULE_CRYPTO_RSA
#define XRT_MODULE_CRYPTO_RSA_PRIVATE
#define XRT_MODULE_CRYPTO_RSA_PKCS1_SIGN
#define XRT_MODULE_CRYPTO_ECDSA_P256_DER
#define XRT_MODULE_CRYPTO_ECDSA_P256_SIGN_DER
#define XRT_MODULE_PEM
#define XRT_MODULE_ASN1_DER
#define XRT_MODULE_TIME
#define XRT_MODULE_STRING
#define XRT_MODULE_ERROR

#include <xrt.h>

#endif
