


#define MMU_USE_PAMM
#define MMU_USE_SAMM
#define MMU_USE_MBMU
#define MMU_USE_BSMM
#define MMU_USE_MMU256
#define MMU_USE_MMU64K
#define MMU_USE_MM256
#define MMU_USE_MM64K
#define MMU_USE_MP256
#define MMU_USE_MP64K
#define MMU_USE_SSSTK
#define MMU_USE_PSSTK
#define MMU_USE_SDSTK
#define MMU_USE_PDSTK
#define MMU_USE_LLIST_BASE
#define MMU_USE_LLIST
#define MMU_USE_AVLTREE_BASE
#define MMU_USE_AVLTREE
#define MMU_USE_RBTREE_BASE
#define MMU_USE_RBTREE
#define MMU_USE_HASH32
#define MMU_USE_HASH64
#define MMU_USE_AVLHT32
#define MMU_USE_AVLHT64
#define MMU_USE_RBHT32
#define MMU_USE_RBHT64
#define MMU_USE_TREE
#define MMU_USE_DOM
#define MMU_USE_GRID
#define MMU_USE_CSQUE
#define MMU_USE_EEQUE
#define MMU_USE_PRQUE
#define MMU_USE_DGRAPH
#define MMU_USE_UGRAPH


