/* 此文件由 tools/generate_extension_features.py 生成，请勿直接修改。 */
#ifndef XACME_FEATURES_H
#define XACME_FEATURES_H

/* acme_obtain 及其直接依赖。 */
#if defined(XACME_MODULE_ALL) || defined(XACME_MODULE_ACME_OBTAIN)
#ifndef XACME_FEATURE_ACME_OBTAIN
#define XACME_FEATURE_ACME_OBTAIN
#endif
#ifndef XACME_MODULE_ACME_CORE
#define XACME_MODULE_ACME_CORE
#endif
#ifndef XACME_MODULE_ACME_FLOW
#define XACME_MODULE_ACME_FLOW
#endif
#ifndef XACME_MODULE_ACME_STORE
#define XACME_MODULE_ACME_STORE
#endif
#ifndef XACME_MODULE_ACME_HTTP
#define XACME_MODULE_ACME_HTTP
#endif
#ifndef XACME_MODULE_ACME_JOSE
#define XACME_MODULE_ACME_JOSE
#endif
#ifndef XACME_MODULE_ACME_CSR
#define XACME_MODULE_ACME_CSR
#endif
#ifndef XACME_MODULE_ACME_DNS
#define XACME_MODULE_ACME_DNS
#endif
#ifndef XACME_MODULE_DNS_ALI
#define XACME_MODULE_DNS_ALI
#endif
#ifndef XRT_MODULE_JSON
#define XRT_MODULE_JSON
#endif
#ifndef XRT_MODULE_FILE_WHOLE
#define XRT_MODULE_FILE_WHOLE
#endif
#ifndef XRT_MODULE_X509_PARSE
#define XRT_MODULE_X509_PARSE
#endif
#ifndef XRT_MODULE_CRYPTO_SHA256
#define XRT_MODULE_CRYPTO_SHA256
#endif
#ifndef XRT_MODULE_PEM
#define XRT_MODULE_PEM
#endif
#ifndef XRT_MODULE_CODEC_BASE64
#define XRT_MODULE_CODEC_BASE64
#endif
#ifndef XRT_MODULE_TIME
#define XRT_MODULE_TIME
#endif
#ifndef XRT_MODULE_BUFFER
#define XRT_MODULE_BUFFER
#endif
#ifndef XRT_MODULE_DIR
#define XRT_MODULE_DIR
#endif
#endif

/* dns_huawei 及其直接依赖。 */
#if defined(XACME_MODULE_ALL) || defined(XACME_MODULE_DNS_HUAWEI)
#ifndef XACME_FEATURE_DNS_HUAWEI
#define XACME_FEATURE_DNS_HUAWEI
#endif
#ifndef XACME_MODULE_ACME_DNS
#define XACME_MODULE_ACME_DNS
#endif
#ifndef XACME_MODULE_ACME_HTTP
#define XACME_MODULE_ACME_HTTP
#endif
#ifndef XRT_MODULE_JSON
#define XRT_MODULE_JSON
#endif
#ifndef XRT_MODULE_CRYPTO_SHA256
#define XRT_MODULE_CRYPTO_SHA256
#endif
#ifndef XRT_MODULE_CRYPTO_HMAC_SHA256
#define XRT_MODULE_CRYPTO_HMAC_SHA256
#endif
#ifndef XRT_MODULE_TIME
#define XRT_MODULE_TIME
#endif
#ifndef XRT_MODULE_BUFFER
#define XRT_MODULE_BUFFER
#endif
#endif

/* dns_aws 及其直接依赖。 */
#if defined(XACME_MODULE_ALL) || defined(XACME_MODULE_DNS_AWS)
#ifndef XACME_FEATURE_DNS_AWS
#define XACME_FEATURE_DNS_AWS
#endif
#ifndef XACME_MODULE_ACME_DNS
#define XACME_MODULE_ACME_DNS
#endif
#ifndef XACME_MODULE_ACME_HTTP
#define XACME_MODULE_ACME_HTTP
#endif
#ifndef XRT_MODULE_CRYPTO_SHA256
#define XRT_MODULE_CRYPTO_SHA256
#endif
#ifndef XRT_MODULE_CRYPTO_HMAC_SHA256
#define XRT_MODULE_CRYPTO_HMAC_SHA256
#endif
#ifndef XRT_MODULE_TIME
#define XRT_MODULE_TIME
#endif
#ifndef XRT_MODULE_BUFFER
#define XRT_MODULE_BUFFER
#endif
#endif

/* dns_tencent 及其直接依赖。 */
#if defined(XACME_MODULE_ALL) || defined(XACME_MODULE_DNS_TENCENT)
#ifndef XACME_FEATURE_DNS_TENCENT
#define XACME_FEATURE_DNS_TENCENT
#endif
#ifndef XACME_MODULE_ACME_DNS
#define XACME_MODULE_ACME_DNS
#endif
#ifndef XACME_MODULE_ACME_HTTP
#define XACME_MODULE_ACME_HTTP
#endif
#ifndef XRT_MODULE_JSON
#define XRT_MODULE_JSON
#endif
#ifndef XRT_MODULE_CRYPTO_SHA256
#define XRT_MODULE_CRYPTO_SHA256
#endif
#ifndef XRT_MODULE_CRYPTO_HMAC_SHA256
#define XRT_MODULE_CRYPTO_HMAC_SHA256
#endif
#ifndef XRT_MODULE_TIME
#define XRT_MODULE_TIME
#endif
#ifndef XRT_MODULE_BUFFER
#define XRT_MODULE_BUFFER
#endif
#endif

/* dns_cf 及其直接依赖。 */
#if defined(XACME_MODULE_ALL) || defined(XACME_MODULE_DNS_CF)
#ifndef XACME_FEATURE_DNS_CF
#define XACME_FEATURE_DNS_CF
#endif
#ifndef XACME_MODULE_ACME_DNS
#define XACME_MODULE_ACME_DNS
#endif
#ifndef XACME_MODULE_ACME_HTTP
#define XACME_MODULE_ACME_HTTP
#endif
#ifndef XRT_MODULE_JSON
#define XRT_MODULE_JSON
#endif
#ifndef XRT_MODULE_BUFFER
#define XRT_MODULE_BUFFER
#endif
#endif

/* acme_flow 及其直接依赖。 */
#if defined(XACME_MODULE_ALL) || defined(XACME_MODULE_ACME_FLOW)
#ifndef XACME_FEATURE_ACME_FLOW
#define XACME_FEATURE_ACME_FLOW
#endif
#ifndef XACME_MODULE_ACME_HTTP
#define XACME_MODULE_ACME_HTTP
#endif
#ifndef XACME_MODULE_ACME_JOSE
#define XACME_MODULE_ACME_JOSE
#endif
#ifndef XACME_MODULE_ACME_CSR
#define XACME_MODULE_ACME_CSR
#endif
#ifndef XACME_MODULE_ACME_DNS
#define XACME_MODULE_ACME_DNS
#endif
#ifndef XRT_MODULE_JSON
#define XRT_MODULE_JSON
#endif
#ifndef XACME_MODULE_DNS_ALI
#define XACME_MODULE_DNS_ALI
#endif
#ifndef XACME_MODULE_ACME_CORE
#define XACME_MODULE_ACME_CORE
#endif
#ifndef XACME_MODULE_ACME_STORE
#define XACME_MODULE_ACME_STORE
#endif
#endif

/* acme_store 及其直接依赖。 */
#if defined(XACME_MODULE_ALL) || defined(XACME_MODULE_ACME_STORE)
#ifndef XACME_FEATURE_ACME_STORE
#define XACME_FEATURE_ACME_STORE
#endif
#ifndef XACME_MODULE_ACME_CORE
#define XACME_MODULE_ACME_CORE
#endif
#ifndef XRT_MODULE_FILE
#define XRT_MODULE_FILE
#endif
#ifndef XRT_MODULE_FILE_WHOLE
#define XRT_MODULE_FILE_WHOLE
#endif
#ifndef XRT_MODULE_X509_PARSE
#define XRT_MODULE_X509_PARSE
#endif
#ifndef XRT_MODULE_CRYPTO_SHA256
#define XRT_MODULE_CRYPTO_SHA256
#endif
#ifndef XRT_MODULE_PEM
#define XRT_MODULE_PEM
#endif
#ifndef XRT_MODULE_CODEC_BASE64
#define XRT_MODULE_CODEC_BASE64
#endif
#ifndef XRT_MODULE_TIME
#define XRT_MODULE_TIME
#endif
#ifndef XRT_MODULE_BUFFER
#define XRT_MODULE_BUFFER
#endif
#ifndef XRT_MODULE_DIR
#define XRT_MODULE_DIR
#endif
#endif

/* acme_core 及其直接依赖。 */
#if defined(XACME_MODULE_ALL) || defined(XACME_MODULE_ACME_CORE)
#ifndef XACME_FEATURE_ACME_CORE
#define XACME_FEATURE_ACME_CORE
#endif
#ifndef XACME_MODULE_ACME_DNS
#define XACME_MODULE_ACME_DNS
#endif
#endif

/* dns_ali 及其直接依赖。 */
#if defined(XACME_MODULE_ALL) || defined(XACME_MODULE_DNS_ALI)
#ifndef XACME_FEATURE_DNS_ALI
#define XACME_FEATURE_DNS_ALI
#endif
#ifndef XACME_MODULE_ACME_DNS
#define XACME_MODULE_ACME_DNS
#endif
#ifndef XACME_MODULE_ACME_HTTP
#define XACME_MODULE_ACME_HTTP
#endif
#ifndef XRT_MODULE_JSON
#define XRT_MODULE_JSON
#endif
#ifndef XRT_MODULE_CODEC_BASE64
#define XRT_MODULE_CODEC_BASE64
#endif
#ifndef XRT_MODULE_CRYPTO_SHA256
#define XRT_MODULE_CRYPTO_SHA256
#endif
#ifndef XRT_MODULE_CRYPTO_HMAC_SHA256
#define XRT_MODULE_CRYPTO_HMAC_SHA256
#endif
#ifndef XRT_MODULE_TIME
#define XRT_MODULE_TIME
#endif
#ifndef XRT_MODULE_BUFFER
#define XRT_MODULE_BUFFER
#endif
#endif

/* acme_dns 及其直接依赖。 */
#if defined(XACME_MODULE_ALL) || defined(XACME_MODULE_ACME_DNS)
#ifndef XACME_FEATURE_ACME_DNS
#define XACME_FEATURE_ACME_DNS
#endif
#ifndef XRT_MODULE_NET_ENGINE
#define XRT_MODULE_NET_ENGINE
#endif
#ifndef XRT_MODULE_NET_UDP
#define XRT_MODULE_NET_UDP
#endif
#ifndef XRT_MODULE_NET_UDP_SYNC
#define XRT_MODULE_NET_UDP_SYNC
#endif
#ifndef XRT_MODULE_RANDOM
#define XRT_MODULE_RANDOM
#endif
#ifndef XRT_MODULE_RANDOM_DEFAULT
#define XRT_MODULE_RANDOM_DEFAULT
#endif
#ifndef XRT_MODULE_TIME
#define XRT_MODULE_TIME
#endif
#ifndef XRT_MODULE_BUFFER
#define XRT_MODULE_BUFFER
#endif
#ifndef XRT_MODULE_ARRAY
#define XRT_MODULE_ARRAY
#endif
#endif

/* acme_csr 及其直接依赖。 */
#if defined(XACME_MODULE_ALL) || defined(XACME_MODULE_ACME_CSR)
#ifndef XACME_FEATURE_ACME_CSR
#define XACME_FEATURE_ACME_CSR
#endif
#ifndef XRT_MODULE_BUFFER
#define XRT_MODULE_BUFFER
#endif
#ifndef XRT_MODULE_ASN1_DER
#define XRT_MODULE_ASN1_DER
#endif
#ifndef XRT_MODULE_PEM
#define XRT_MODULE_PEM
#endif
#ifndef XRT_MODULE_CODEC_BASE64
#define XRT_MODULE_CODEC_BASE64
#endif
#ifndef XRT_MODULE_CRYPTO_P256
#define XRT_MODULE_CRYPTO_P256
#endif
#ifndef XRT_MODULE_CRYPTO_ECDSA_P256_SIGN_DER
#define XRT_MODULE_CRYPTO_ECDSA_P256_SIGN_DER
#endif
#ifndef XRT_MODULE_CRYPTO_RSA_PKCS1_SIGN
#define XRT_MODULE_CRYPTO_RSA_PKCS1_SIGN
#endif
#ifndef XACME_MODULE_ACME_JOSE
#define XACME_MODULE_ACME_JOSE
#endif
#endif

/* acme_jose 及其直接依赖。 */
#if defined(XACME_MODULE_ALL) || defined(XACME_MODULE_ACME_JOSE)
#ifndef XACME_FEATURE_ACME_JOSE
#define XACME_FEATURE_ACME_JOSE
#endif
#ifndef XRT_MODULE_BUFFER
#define XRT_MODULE_BUFFER
#endif
#ifndef XRT_MODULE_CODEC_BASE64
#define XRT_MODULE_CODEC_BASE64
#endif
#ifndef XRT_MODULE_CRYPTO_SHA256
#define XRT_MODULE_CRYPTO_SHA256
#endif
#ifndef XRT_MODULE_CRYPTO_HMAC_SHA256
#define XRT_MODULE_CRYPTO_HMAC_SHA256
#endif
#ifndef XRT_MODULE_CRYPTO_P256_KEYPAIR
#define XRT_MODULE_CRYPTO_P256_KEYPAIR
#endif
#ifndef XRT_MODULE_CRYPTO_ECDSA_P256_SIGN
#define XRT_MODULE_CRYPTO_ECDSA_P256_SIGN
#endif
#endif

/* acme_http 及其直接依赖。 */
#if defined(XACME_MODULE_ALL) || defined(XACME_MODULE_ACME_HTTP)
#ifndef XACME_FEATURE_ACME_HTTP
#define XACME_FEATURE_ACME_HTTP
#endif
#ifndef XRT_MODULE_BUFFER
#define XRT_MODULE_BUFFER
#endif
#ifndef XRT_MODULE_HTTP
#define XRT_MODULE_HTTP
#endif
#ifndef XRT_MODULE_HTTP1_HEAD
#define XRT_MODULE_HTTP1_HEAD
#endif
#ifndef XRT_MODULE_HTTP1_BODY
#define XRT_MODULE_HTTP1_BODY
#endif
#ifndef XRT_MODULE_HTTP1_NET
#define XRT_MODULE_HTTP1_NET
#endif
#ifndef XRT_MODULE_NET_ENGINE
#define XRT_MODULE_NET_ENGINE
#endif
#ifndef XRT_MODULE_NET_RESOLVER
#define XRT_MODULE_NET_RESOLVER
#endif
#ifndef XRT_MODULE_NET_TCP
#define XRT_MODULE_NET_TCP
#endif
#ifndef XRT_MODULE_NET_TCP_DIAL
#define XRT_MODULE_NET_TCP_DIAL
#endif
#ifndef XRT_MODULE_TLS_STREAM
#define XRT_MODULE_TLS_STREAM
#endif
#ifndef XRT_MODULE_TLS_STREAM_DIAL
#define XRT_MODULE_TLS_STREAM_DIAL
#endif
#ifndef XRT_MODULE_TLS_STREAM_DIAL_FUTURE
#define XRT_MODULE_TLS_STREAM_DIAL_FUTURE
#endif
#ifndef XRT_MODULE_TLS_CLIENT
#define XRT_MODULE_TLS_CLIENT
#endif
#ifndef XRT_MODULE_TLS_CLIENT_VERIFY
#define XRT_MODULE_TLS_CLIENT_VERIFY
#endif
#ifndef XRT_MODULE_TLS_VERIFY
#define XRT_MODULE_TLS_VERIFY
#endif
#ifndef XRT_MODULE_X509_STORE
#define XRT_MODULE_X509_STORE
#endif
#ifndef XRT_MODULE_X509_STORE_SYSTEM
#define XRT_MODULE_X509_STORE_SYSTEM
#endif
#ifndef XRT_MODULE_FUTURE
#define XRT_MODULE_FUTURE
#endif
#ifndef XRT_MODULE_FUTURE_BRIDGE
#define XRT_MODULE_FUTURE_BRIDGE
#endif
#ifndef XRT_MODULE_CANCEL
#define XRT_MODULE_CANCEL
#endif
#ifndef XRT_MODULE_TIME
#define XRT_MODULE_TIME
#endif
#ifndef XRT_MODULE_THREAD
#define XRT_MODULE_THREAD
#endif
#ifndef XRT_MODULE_NET_TCP_FUTURE
#define XRT_MODULE_NET_TCP_FUTURE
#endif
#ifndef XRT_MODULE_TLS_STREAM_FUTURE
#define XRT_MODULE_TLS_STREAM_FUTURE
#endif
#ifndef XRT_MODULE_NET_TCP_DIAL_FUTURE
#define XRT_MODULE_NET_TCP_DIAL_FUTURE
#endif
#ifndef XRT_MODULE_TLS_NEGOTIATE
#define XRT_MODULE_TLS_NEGOTIATE
#endif
#ifndef XRT_MODULE_TLS_POLICY
#define XRT_MODULE_TLS_POLICY
#endif
#ifndef XRT_MODULE_TLS_CONTEXT
#define XRT_MODULE_TLS_CONTEXT
#endif
#ifndef XRT_MODULE_TLS_RECORD
#define XRT_MODULE_TLS_RECORD
#endif
#ifndef XRT_MODULE_TLS_RECORD_AES
#define XRT_MODULE_TLS_RECORD_AES
#endif
#ifndef XRT_MODULE_TLS_SCHEDULE_SHA256
#define XRT_MODULE_TLS_SCHEDULE_SHA256
#endif
#ifndef XRT_MODULE_TLS_SCHEDULE_SHA384
#define XRT_MODULE_TLS_SCHEDULE_SHA384
#endif
#ifndef XRT_MODULE_TLS_KEY_EXCHANGE_X25519
#define XRT_MODULE_TLS_KEY_EXCHANGE_X25519
#endif
#ifndef XRT_MODULE_TLS_KEY_EXCHANGE_P256
#define XRT_MODULE_TLS_KEY_EXCHANGE_P256
#endif
#ifndef XRT_MODULE_TLS_KEY_EXCHANGE_P384
#define XRT_MODULE_TLS_KEY_EXCHANGE_P384
#endif
#endif

#endif /* XACME_FEATURES_H */
