/* extracted runtime state surface */

static char* g_sXsConfigFile = NULL;
static bool g_bXsConfigFileOwned = FALSE;
static xtime g_tXsStartTime = 0;
static double g_fXsStartTick = 0.0;
static uint32 g_iXsEngineWorkers = 0;
static uint32 g_iXsRuntimeServerCount = 0;

static inline bool XS_RuntimeStatsEnabled(void)
{
#ifdef XRT_MEM_DEBUG
	return TRUE;
#else
	return FALSE;
#endif
}

static inline bool XS_RuntimeGovernEnabled(void)
{
#ifdef XRT_MEM_DEBUG
	return TRUE;
#else
	return FALSE;
#endif
}

static volatile int64 g_iXsHttpReqCount = 0;
static volatile int64 g_iXsHttpManageReqCount = 0;
static volatile int64 g_iXsHttpAppReqCount = 0;
static volatile int64 g_iXsHttpResp2xxCount = 0;
static volatile int64 g_iXsHttpResp3xxCount = 0;
static volatile int64 g_iXsHttpResp4xxCount = 0;
static volatile int64 g_iXsHttpResp5xxCount = 0;
static volatile int64 g_iXsHttpConnCurrent = 0;
static volatile int64 g_iXsHttpConnPeak = 0;
static volatile int64 g_iXsHttpIdleCloseCount = 0;
static volatile int64 g_iXsHttpConnLimitCloseCount = 0;
static volatile int64 g_iXsHttpStopCleanupCount = 0;
static volatile int64 g_iXsHttpRejectCount = 0;
static volatile int64 g_iXsHttpHeaderLimitRejectCount = 0;
static volatile int64 g_iXsHttpBodyLimitRejectCount = 0;
static volatile int64 g_iXsHttpPathLimitRejectCount = 0;
static volatile int64 g_iXsHttpApiDisabledRejectCount = 0;
static volatile int64 g_iXsHttpMethodRejectCount = 0;
static volatile int64 g_iXsHttpHostNotFoundRejectCount = 0;
static volatile int64 g_iXsHttpReloadBusyRejectCount = 0;
static volatile int64 g_iXsHttpReloadFailedRejectCount = 0;
static volatile int64 g_iXsHttpCheckConfigFailedRejectCount = 0;
static volatile int64 g_iXsHttpBusBadRequestRejectCount = 0;
static volatile int64 g_iXsHttpBusNotFoundRejectCount = 0;
static volatile int64 g_iXsHttpBusLimitRejectCount = 0;
static volatile int64 g_iXsHttpBusFailedRejectCount = 0;
static volatile int64 g_iXsHttpMethodGetCount = 0;
static volatile int64 g_iXsHttpMethodPostCount = 0;
static volatile int64 g_iXsHttpMethodHeadCount = 0;
static volatile int64 g_iXsHttpMethodOtherCount = 0;
static volatile int64 g_iXsHttpLastMethodType = 0;
static volatile int64 g_iXsHttpLastAppMethodType = 0;
static volatile int64 g_iXsHttpTimeTotalMS = 0;
static volatile int64 g_iXsHttpTimeMaxMS = 0;
static volatile int64 g_iXsHttpLastTimeMS = 0;
static volatile int64 g_iXsHttpLastAppTimeMS = 0;
static volatile int64 g_iXsHttpLastStatusCode = 0;
static volatile int64 g_iXsHttpLastAppStatusCode = 0;
static volatile int64 g_iXsHttpLastRejectStatus = 0;
static xtime g_tXsHttpLastRequestTime = 0;
static xtime g_tXsHttpLastAppRequestTime = 0;
static xtime g_tXsHttpLastIdleCloseTime = 0;
static xtime g_tXsHttpLastConnLimitCloseTime = 0;
static xtime g_tXsHttpLastStopCleanupTime = 0;
static xtime g_tXsHttpLastRejectTime = 0;
static xtime g_tXsHttpLastHeaderLimitRejectTime = 0;
static xtime g_tXsHttpLastBodyLimitRejectTime = 0;
static xtime g_tXsHttpLastPathLimitRejectTime = 0;
static xtime g_tXsHttpLastApiDisabledRejectTime = 0;
static xtime g_tXsHttpLastMethodRejectTime = 0;
static xtime g_tXsHttpLastHostNotFoundRejectTime = 0;
static xtime g_tXsHttpLastReloadBusyRejectTime = 0;
static xtime g_tXsHttpLastReloadFailedRejectTime = 0;
static xtime g_tXsHttpLastCheckConfigFailedRejectTime = 0;
static xtime g_tXsHttpLastBusBadRequestRejectTime = 0;
static xtime g_tXsHttpLastBusNotFoundRejectTime = 0;
static xtime g_tXsHttpLastBusLimitRejectTime = 0;
static xtime g_tXsHttpLastBusFailedRejectTime = 0;
static volatile int64 g_iXsHttpLastStopCleanupClosed = 0;
static volatile int64 g_iXsHttpLastStopCleanupRemain = 0;
static volatile int64 g_iXsHttpLastBodyLen = 0;
static volatile int64 g_iXsHttpLastAppBodyLen = 0;
static volatile int64 g_iXsHttpLastHeaderCount = 0;
static volatile int64 g_iXsHttpLastAppHeaderCount = 0;
static volatile int64 g_iXsHttpLastQueryLen = 0;
static volatile int64 g_iXsHttpLastAppQueryLen = 0;
static char g_sXsHttpLastPath[1024] = {0};
static char g_sXsHttpLastTarget[2048] = {0};
static char g_sXsHttpLastRemote[128] = {0};
static char g_sXsHttpLastContentType[128] = {0};
static char g_sXsHttpLastHost[256] = {0};
static char g_sXsHttpLastUserAgent[256] = {0};
static char g_sXsHttpLastReferer[512] = {0};
static char g_sXsHttpLastOrigin[256] = {0};
static char g_sXsHttpLastAccept[256] = {0};
static char g_sXsHttpLastAcceptEncoding[256] = {0};
static char g_sXsHttpLastCookie[512] = {0};
static char g_sXsHttpLastForwardedFor[256] = {0};
static char g_sXsHttpLastRealIP[128] = {0};
static char g_sXsHttpLastConnection[128] = {0};
static char g_sXsHttpLastCacheControl[256] = {0};
static char g_sXsHttpLastVersion[32] = {0};
static char g_sXsHttpLastAppPath[1024] = {0};
static char g_sXsHttpLastAppTarget[2048] = {0};
static char g_sXsHttpLastAppRemote[128] = {0};
static char g_sXsHttpLastAppContentType[128] = {0};
static char g_sXsHttpLastAppHost[256] = {0};
static char g_sXsHttpLastAppUserAgent[256] = {0};
static char g_sXsHttpLastAppReferer[512] = {0};
static char g_sXsHttpLastAppOrigin[256] = {0};
static char g_sXsHttpLastAppAccept[256] = {0};
static char g_sXsHttpLastAppAcceptEncoding[256] = {0};
static char g_sXsHttpLastAppCookie[512] = {0};
static char g_sXsHttpLastAppForwardedFor[256] = {0};
static char g_sXsHttpLastAppRealIP[128] = {0};
static char g_sXsHttpLastAppConnection[128] = {0};
static char g_sXsHttpLastAppCacheControl[256] = {0};
static char g_sXsHttpLastAppVersion[32] = {0};
static char g_sXsHttpLastRejectReason[128] = {0};
static char g_sXsHttpLastRejectRemote[128] = {0};
static volatile int64 g_iXsWsConnCurrent = 0;
static volatile int64 g_iXsWsConnPeak = 0;
static volatile int64 g_iXsWsOpenCount = 0;
static volatile int64 g_iXsWsCloseCount = 0;
static volatile int64 g_iXsWsTextCount = 0;
static volatile int64 g_iXsWsBinaryCount = 0;
static volatile int64 g_iXsWsPingCount = 0;
static volatile int64 g_iXsWsPongCount = 0;
static volatile int64 g_iXsWsErrorCount = 0;
static volatile int64 g_iXsWsInvalidCount = 0;
static volatile int64 g_iXsWsLastErrorCode = 0;
static volatile int64 g_iXsWsLastCloseReason = 0;
static volatile int64 g_iXsWsLastFrameType = 0;
static volatile int64 g_iXsWsLastBytes = 0;
static volatile int64 g_iXsWsIdleCloseCount = 0;
static volatile int64 g_iXsWsConnLimitCloseCount = 0;
static volatile int64 g_iXsWsMessageLimitCloseCount = 0;
static volatile int64 g_iXsWsStopCleanupCount = 0;
static volatile int64 g_iXsWsRejectCount = 0;
static volatile int64 g_iXsWsServerStoppingRejectCount = 0;
static volatile int64 g_iXsWsConnLimitRejectCount = 0;
static volatile int64 g_iXsWsMessageLimitRejectCount = 0;
static volatile int64 g_iXsWsInvalidRejectCount = 0;
static volatile int64 g_iXsWsOtherRejectCount = 0;
static xtime g_tXsWsLastTime = 0;
static xtime g_tXsWsLastCloseTime = 0;
static xtime g_tXsWsLastErrorTime = 0;
static xtime g_tXsWsLastInvalidTime = 0;
static xtime g_tXsWsLastIdleCloseTime = 0;
static xtime g_tXsWsLastConnLimitCloseTime = 0;
static xtime g_tXsWsLastMessageLimitCloseTime = 0;
static xtime g_tXsWsLastStopCleanupTime = 0;
static xtime g_tXsWsLastRejectTime = 0;
static xtime g_tXsWsLastServerStoppingRejectTime = 0;
static xtime g_tXsWsLastConnLimitRejectTime = 0;
static xtime g_tXsWsLastMessageLimitRejectTime = 0;
static xtime g_tXsWsLastInvalidRejectTime = 0;
static xtime g_tXsWsLastOtherRejectTime = 0;
static volatile int64 g_iXsWsLastStopCleanupClosed = 0;
static volatile int64 g_iXsWsLastStopCleanupRemain = 0;
static char g_sXsWsLastText[256] = {0};
static char g_sXsWsLastRemote[128] = {0};
static char g_sXsWsLastInvalidReason[128] = {0};
static char g_sXsWsLastInvalidRemote[128] = {0};
static char g_sXsWsLastRejectReason[128] = {0};
static char g_sXsWsLastRejectRemote[128] = {0};
static char g_sXsWsLastErrorRemote[128] = {0};
static volatile int64 g_iXsXtpConnCurrent = 0;
static volatile int64 g_iXsXtpConnPeak = 0;
static volatile int64 g_iXsXtpOpenCount = 0;
static volatile int64 g_iXsXtpCloseCount = 0;
static volatile int64 g_iXsXtpErrorCount = 0;
static volatile int64 g_iXsXtpLastErrorCode = 0;
static volatile int64 g_iXsXtpInvalidCount = 0;
static volatile int64 g_iXsXtpMsgCount = 0;
static volatile int64 g_iXsXtpReqCount = 0;
static volatile int64 g_iXsXtpRespCount = 0;
static volatile int64 g_iXsXtpPushCount = 0;
static volatile int64 g_iXsXtpEventCount = 0;
static volatile int64 g_iXsXtpSendCount = 0;
static volatile int64 g_iXsXtpRecvBytes = 0;
static volatile int64 g_iXsXtpSendBytes = 0;
static volatile int64 g_iXsXtpLastBytes = 0;
static volatile int64 g_iXsXtpIdleCloseCount = 0;
static volatile int64 g_iXsXtpConnLimitCloseCount = 0;
static volatile int64 g_iXsXtpRecvLimitCloseCount = 0;
static volatile int64 g_iXsXtpStopCleanupCount = 0;
static volatile int64 g_iXsXtpRejectCount = 0;
static volatile int64 g_iXsXtpServerStoppingRejectCount = 0;
static volatile int64 g_iXsXtpConnLimitRejectCount = 0;
static volatile int64 g_iXsXtpRecvLimitRejectCount = 0;
static volatile int64 g_iXsXtpInvalidRejectCount = 0;
static volatile int64 g_iXsXtpOtherRejectCount = 0;
static volatile int64 g_iXsXtpLastMsgType = 0;
static volatile int64 g_iXsXtpLastStatus = 0;
static volatile int64 g_iXsXtpLastMsgID = 0;
static volatile int64 g_iXsXtpLastFlags = 0;
static volatile int64 g_iXsXtpLastParamCount = 0;
static volatile int64 g_iXsXtpLastBodySize = 0;
static xtime g_tXsXtpLastErrorTime = 0;
static xtime g_tXsXtpLastInvalidTime = 0;
static xtime g_tXsXtpLastIdleCloseTime = 0;
static xtime g_tXsXtpLastConnLimitCloseTime = 0;
static xtime g_tXsXtpLastRecvLimitCloseTime = 0;
static xtime g_tXsXtpLastStopCleanupTime = 0;
static xtime g_tXsXtpLastRejectTime = 0;
static xtime g_tXsXtpLastServerStoppingRejectTime = 0;
static xtime g_tXsXtpLastConnLimitRejectTime = 0;
static xtime g_tXsXtpLastRecvLimitRejectTime = 0;
static xtime g_tXsXtpLastInvalidRejectTime = 0;
static xtime g_tXsXtpLastOtherRejectTime = 0;
static volatile int64 g_iXsXtpLastStopCleanupClosed = 0;
static volatile int64 g_iXsXtpLastStopCleanupRemain = 0;
static xtime g_tXsXtpLastTime = 0;
static char g_sXsXtpLastCmd[256] = {0};
static char g_sXsXtpLastRemote[128] = {0};
static char g_sXsXtpLastInvalidReason[128] = {0};
static char g_sXsXtpLastInvalidRemote[128] = {0};
static char g_sXsXtpLastRejectReason[128] = {0};
static char g_sXsXtpLastRejectRemote[128] = {0};
static char g_sXsXtpLastErrorRemote[128] = {0};
static volatile int64 g_iXsUdpRecvCount = 0;
static volatile int64 g_iXsUdpSendCount = 0;
static volatile int64 g_iXsUdpErrorCount = 0;
static volatile int64 g_iXsUdpRejectCount = 0;
static volatile int64 g_iXsUdpRecvLimitRejectCount = 0;
static volatile int64 g_iXsUdpLastErrorCode = 0;
static volatile int64 g_iXsUdpLastBytes = 0;
static volatile int64 g_iXsUdpLastRejectBytes = 0;
static volatile int64 g_iXsUdpRecvBytes = 0;
static volatile int64 g_iXsUdpSendBytes = 0;
static xtime g_tXsUdpLastTime = 0;
static xtime g_tXsUdpLastErrorTime = 0;
static xtime g_tXsUdpLastRejectTime = 0;
static xtime g_tXsUdpLastRecvLimitRejectTime = 0;
static char g_sXsUdpLastFrom[128] = {0};
static char g_sXsUdpLastText[256] = {0};
static char g_sXsUdpLastRejectReason[64] = {0};
static char g_sXsUdpLastRejectFrom[128] = {0};
static volatile int64 g_iXsCustomConnCurrent = 0;
static volatile int64 g_iXsCustomConnPeak = 0;
static volatile int64 g_iXsCustomOpenCount = 0;
static volatile int64 g_iXsCustomCloseCount = 0;
static volatile int64 g_iXsCustomErrorCount = 0;
static volatile int64 g_iXsCustomInvalidCount = 0;
static volatile int64 g_iXsCustomLastCloseReason = 0;
static volatile int64 g_iXsCustomLastErrorCode = 0;
static volatile int64 g_iXsCustomRecvCount = 0;
static volatile int64 g_iXsCustomSendCount = 0;
static volatile int64 g_iXsCustomRecvBytes = 0;
static volatile int64 g_iXsCustomSendBytes = 0;
static volatile int64 g_iXsCustomLastBytes = 0;
static volatile int64 g_iXsCustomIdleCloseCount = 0;
static volatile int64 g_iXsCustomConnLimitCloseCount = 0;
static volatile int64 g_iXsCustomRecvLimitCloseCount = 0;
static volatile int64 g_iXsCustomStopCleanupCount = 0;
static volatile int64 g_iXsCustomRejectCount = 0;
static volatile int64 g_iXsCustomServerStoppingRejectCount = 0;
static volatile int64 g_iXsCustomConnLimitRejectCount = 0;
static volatile int64 g_iXsCustomRecvLimitRejectCount = 0;
static volatile int64 g_iXsCustomInvalidRejectCount = 0;
static volatile int64 g_iXsCustomOtherRejectCount = 0;
static xtime g_tXsCustomLastTime = 0;
static xtime g_tXsCustomLastCloseTime = 0;
static xtime g_tXsCustomLastErrorTime = 0;
static xtime g_tXsCustomLastInvalidTime = 0;
static xtime g_tXsCustomLastIdleCloseTime = 0;
static xtime g_tXsCustomLastConnLimitCloseTime = 0;
static xtime g_tXsCustomLastRecvLimitCloseTime = 0;
static xtime g_tXsCustomLastStopCleanupTime = 0;
static xtime g_tXsCustomLastRejectTime = 0;
static xtime g_tXsCustomLastServerStoppingRejectTime = 0;
static xtime g_tXsCustomLastConnLimitRejectTime = 0;
static xtime g_tXsCustomLastRecvLimitRejectTime = 0;
static xtime g_tXsCustomLastInvalidRejectTime = 0;
static xtime g_tXsCustomLastOtherRejectTime = 0;
static volatile int64 g_iXsCustomLastStopCleanupClosed = 0;
static volatile int64 g_iXsCustomLastStopCleanupRemain = 0;
static char g_sXsCustomLastText[256] = {0};
static char g_sXsCustomLastRemote[128] = {0};
static char g_sXsCustomLastInvalidReason[128] = {0};
static char g_sXsCustomLastInvalidRemote[128] = {0};
static char g_sXsCustomLastRejectReason[128] = {0};
static char g_sXsCustomLastRejectRemote[128] = {0};
static char g_sXsCustomLastErrorRemote[128] = {0};
static volatile int64 g_iXsCheckConfigTotalCount = 0;
static volatile int64 g_iXsCheckConfigSuccessCount = 0;
static volatile int64 g_iXsCheckConfigFailureCount = 0;
static volatile int64 g_iXsCheckConfigLastServerCount = 0;
static xtime g_tXsCheckConfigLastTime = 0;
static volatile long g_iXsCheckConfigStateLock = 0;
static bool g_bXsCheckConfigHasResult = FALSE;
static bool g_bXsCheckConfigLastResult = FALSE;
static char g_sXsCheckConfigLastFile[1024] = {0};
static char g_sXsCheckConfigLastBase[1024] = {0};
static char g_sXsCheckConfigLastMessage[128] = {0};

typedef struct {
	bool HasResult;
	bool LastResult;
	xtime LastTime;
	int64 iTotalCount;
	int64 iSuccessCount;
	int64 iFailureCount;
	int64 iLastServerCount;
	char sLastFile[1024];
	char sLastBase[1024];
	char sLastMessage[128];
} XS_CheckConfigStatusSnapshot;

typedef struct {
	bool Busy;
	bool Success;
	bool HasResult;
	xtime LastTime;
	int64 iTotalCount;
	int64 iSuccessCount;
	int64 iFailureCount;
	char sServerName[128];
	char sHostName[128];
	char sMessage[256];
} XS_ReloadStatusSnapshot;
