/* xrt 模块闭包：xoauth2 需要的 xrt 核心能力。 */
#ifndef XOAUTH2_XRT_H
#define XOAUTH2_XRT_H

#define XRT_MODULE_CORE
#define XRT_MODULE_ERROR
#define XRT_MODULE_STRING
#define XRT_MODULE_TIME
#define XRT_MODULE_RANDOM
#define XRT_MODULE_RANDOM_SECURE
#define XRT_MODULE_JSON_READ
#define XRT_MODULE_JSON_WRITE
#define XRT_MODULE_VALUE
#define XRT_MODULE_CODEC_BASE64
#define XRT_MODULE_CRYPTO_CORE
#define XRT_MODULE_CRYPTO_SHA256
#define XRT_MODULE_BUFFER
#define XRT_MODULE_NET_ENGINE
#define XRT_MODULE_NET_RESOLVER
#define XRT_MODULE_NET_TCP_DIAL_SYNC
#define XRT_MODULE_NET_TCP_FUTURE
#define XRT_MODULE_NET_STREAM
#define XRT_MODULE_NET_ADDR
#define XRT_MODULE_TLS_STREAM_DIAL_FUTURE
#define XRT_MODULE_TLS_STREAM_FUTURE
#define XRT_MODULE_TLS_CLIENT_VERIFY
#define XRT_MODULE_TLS_SCHEDULE_SHA256
#define XRT_MODULE_TLS_SCHEDULE_SHA384
#define XRT_MODULE_TLS_KEY_EXCHANGE_X25519
#define XRT_MODULE_TLS_RECORD_AES
#define XRT_MODULE_HTTP1_BODY
#define XRT_MODULE_HTTP1_RESPONSE
#define XRT_MODULE_X509_STORE_SYSTEM
#define XRT_MODULE_FUTURE
#define XRT_MODULE_URL

#include <xrt.h>

#endif
