"""Refresh vendored xrt sources, SDK shims and imports as one recorded snapshot.

python tools/sync_xrt.py --source ../xrt
python tools/sync_xrt.py --check

Upstream files are copied byte-for-byte. The lock records working-tree hashes
as well as HEAD: an uncommitted upstream snapshot is never labelled a release.
The generated registry/shims/imports are xs integration code, not upstream patches.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
from pathlib import Path

from xs_extensions import ROOT, REGISTRY, load_registry

LOCK = ROOT / "lib/xrt_sources.lock.json"
LIBRARIES = ("xjwt", "xoauth2", "xmail", "xsmtp", "xpop3", "ximap",
             "xacme", "xllm", "xllm-session", "xwork")


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def without_comments(text: str) -> str:
    return re.sub(r"//[^\r\n]*", " ",
                  re.sub(r"/\*.*?\*/", " ", text, flags=re.S))


def public_functions_text(headers: list[str], prefix: str) -> list[str]:
    """The public headers contain prototypes, never implementation fragments."""
    pattern = re.compile(r"\b(" + prefix + r"[A-Z]\w*)\s*\([^;{}]*\)\s*;")
    names = set()
    for header in headers:
        names.update(pattern.findall(without_comments(header)))
    if not names:
        raise ValueError(f"no public functions found for {prefix}")
    return sorted(names)


def public_functions(headers: list[Path], prefix: str) -> list[str]:
    return public_functions_text([p.read_text(encoding="utf-8") for p in headers], prefix)


def collect(source: Path) -> dict[str, tuple[Path, bytes]]:
    source = source.resolve(strict=True)
    files = {}

    def add(path: Path, target: str) -> None:
        if not path.resolve(strict=True).is_relative_to(source):
            raise ValueError(f"upstream path escapes source: {path}")
        files[target] = (path, path.read_bytes())

    for name in ("xrt.h", "xrt_decl.h"):
        add(source / "single" / name, "lib/" + name)
    for name in LIBRARIES:
        base = source / "extlibs" / name
        # Older snapshots had flat TUs; current snapshots use manifest sources.
        root_files = {p.name for pattern in ("*.h", "*.c") for p in base.glob(pattern)}
        for relative in sorted(root_files | {"README.md", "LICENSE"}):
            path = base / relative
            if path.is_file():
                add(path, f"lib/{name}/{relative}")
        for directory in ("include", "src", "config"):
            for path in sorted((base / directory).rglob("*")):
                if path.is_file():
                    add(path, f"lib/{name}/" + path.relative_to(base).as_posix())
    return files


def generate_shims(declarations: str, header_names: list[str]) -> dict[str, bytes]:
    features = sorted(set(re.findall(r"XRT_DECLARATIONS_RESTORE_XRT_FEATURE_(\w+)", declarations)))
    if len(features) < 100:
        raise ValueError("incomplete xrt declaration feature inventory")
    lines = ["/* Generated by tools/sync_xrt.py from xrt_decl.h; repeatable include. */"]
    for name in features:
        lines += [f"#if (defined(XRT_MODULE_ALL) || defined(XRT_MODULE_{name})) && !defined(XRT_FEATURE_{name})",
                  f"#define XRT_FEATURE_{name}", "#endif"]
    output = {"lib/xrtshim/xrt/promote.h": ("\n".join(lines) + "\n").encode()}
    shim = b"/* Generated xrt modular header bridge. */\n#include <xrt/promote.h>\n#include <xrt_decl.h>\n"
    for name in header_names + ["xrt.h"]:
        output["lib/xrtshim/xrt/" + name] = shim
    return output


def modular_registry(source: Path, registry: dict) -> dict:
    """Derive native objects and the complete public SDK from upstream manifests.

    Native products compile as separate translation units. No copied single
    implementation or stale xs unity wrapper is allowed to hide missing APIs.
    Preserve xs's extension names and dependency selection contract.
    """
    for name in LIBRARIES:
        base = source / "extlibs" / name
        manifest = json.loads((base / "config/modules.json").read_text(encoding="utf-8"))
        prefix = f"extlibs/{name}/"

        def target(relative: str) -> str:
            if not relative.startswith(prefix):
                raise ValueError(f"{name}: manifest path outside product: {relative}")
            path = source / relative
            if not path.resolve(strict=True).is_relative_to(base.resolve()):
                raise ValueError(f"{name}: manifest path escapes product: {relative}")
            return "lib/" + relative.removeprefix("extlibs/")

        entry = registry[name]
        headers = {p.relative_to(base / "include").as_posix():
                   "lib/" + p.relative_to(source / "extlibs").as_posix()
                   for p in sorted((base / "include").rglob("*.h"))}
        if not headers:
            raise ValueError(f"{name}: no public headers")
        # Retain the former flat TCC spelling for existing consumer scripts.
        if name == "xllm":
            headers["xllm-executor.h"] = headers["xllm/executor.h"]
        sources = sorted({target(p) for m in manifest["modules"] for p in m.get("sources", [])})
        if not sources:
            raise ValueError(f"{name}: no native sources")
        entry["headers"] = headers
        entry["sources"] = [{"path": p} for p in sources]
        entry["feature_macro"] = ["XRT_MODULE_ALL", manifest["module_prefix"] + "ALL"]
        entry["host_includes"] = [f"lib/{name}/include", "lib/xrtshim"]
    return registry


def check_lock(root: Path = ROOT, lock: Path = LOCK) -> None:
    data = json.loads(lock.read_text(encoding="utf-8"))
    if data.get("schema") != 1 or not data.get("files"):
        raise ValueError("invalid xrt source lock")
    for relative, expected in data["files"].items():
        path = (root / relative).resolve()
        if not path.is_relative_to(root.resolve()) or not path.is_file():
            raise ValueError(f"missing or out-of-project locked file: {relative}")
        if digest(path.read_bytes()) != expected["sha256"]:
            raise ValueError(f"xrt snapshot drift: {relative}; sync again instead of patching vendor files")


def refresh(source: Path) -> None:
    source = source.resolve(strict=True)
    commit = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=source, text=True).strip()
    files = collect(source)
    generated = generate_shims(files["lib/xrt_decl.h"][1].decode("utf-8"),
                               [p.name for p in sorted((source / "include/xrt").glob("*.h"))])
    registry = modular_registry(source, load_registry())
    for name in LIBRARIES:
        entry = registry[name]
        headers = [files[p][1].decode("utf-8") for p in entry["headers"].values()]
        prefix = "(?:xrt|xacme)" if name == "xacme" else "xrt" if name in ("xmail", "xsmtp", "xpop3", "ximap") else "xllm" if name == "xllm-session" else name
        # Session headers repeat the companion estimators for consumers. Their
        # implementation/export belongs to xllm, a required dependency.
        names = public_functions_text(headers, prefix)
        if name == "xllm-session":
            companion = public_functions_text([files[p][1].decode("utf-8")
                for p in registry["xllm"]["headers"].values()], "xllm")
            names = sorted(set(names) - set(companion))
        text = "/* Generated by tools/sync_xrt.py from public headers. */\n"
        text += "".join(f"{entry['symbol_macro']}({n})\n" for n in names)
        generated[entry["symbols"]] = text.encode()
    # Do not copy a moving source snapshot. Recheck every captured file first.
    for path, data in files.values():
        if path.read_bytes() != data:
            raise ValueError(f"upstream changed during collection: {path}")
    if subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=source, text=True).strip() != commit:
        raise ValueError("upstream commit changed during collection")
    status = subprocess.check_output(
        ["git", "status", "--porcelain", "--", "single", "extlibs", "include/xrt"],
        cwd=source, text=True, encoding="utf-8")
    # Remove only files owned by the previous snapshot and verify their bytes
    # before changing anything. An edited vendor file requires an explicit
    # reconciliation, never silent deletion during an upstream refresh.
    obsolete = []
    if LOCK.is_file():
        check_lock()
        previous = json.loads(LOCK.read_text(encoding="utf-8"))["files"]
        obsolete = sorted(set(previous) - set(files) - set(generated) -
                          {"src/script/import_xrt.inc", "lib/xrt_version.txt"} -
                          {f"lib/{name}/UPSTREAM.txt" for name in LIBRARIES})
    for relative in obsolete:
        (ROOT / relative).unlink()
    for relative, (_, data) in files.items():
        path = ROOT / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
    for relative, data in generated.items():
        (ROOT / relative).write_bytes(data)
    REGISTRY.write_text(json.dumps(registry, indent=1, ensure_ascii=False) + "\n",
                        encoding="utf-8", newline="\n")
    version = commit + ("-working-tree" if status else "")
    version_text = version + "\nByte-for-byte upstream snapshot; file hashes in xrt_sources.lock.json.\nNo local upstream patches; refresh with python tools/sync_xrt.py --source ../xrt.\n"
    (ROOT / "lib/xrt_version.txt").write_text(version_text, encoding="utf-8", newline="\n")
    generated["lib/xrt_version.txt"] = version_text.encode()
    for name in LIBRARIES:
        relative = f"lib/{name}/UPSTREAM.txt"
        metadata = (f"Source: xrt extlibs/{name}\nSnapshot: {version}\n"
                    "Upstream source bytes and SHA256 are recorded in ../xrt_sources.lock.json.\n"
                    "Native sources, public headers and module configuration are vendored.\n"
                    "Native module sources compile separately; single-header implementations are not used.\n")
        (ROOT / relative).write_text(metadata, encoding="utf-8", newline="\n")
        generated[relative] = metadata.encode()
    import gen_xrt_symbols
    if gen_xrt_symbols.main() != 0:
        raise ValueError("xrt symbol generation failed")
    generated["src/script/import_xrt.inc"] = gen_xrt_symbols.OUTPUT.read_bytes()
    record = {"schema": 1, "upstream_commit": commit, "upstream_working_tree": bool(status), "files": {}}
    for relative, (path, data) in sorted(files.items()):
        record["files"][relative] = {"source": path.relative_to(source).as_posix(), "sha256": digest(data)}
    for relative, data in sorted(generated.items()):
        record["files"][relative] = {"generated": True, "sha256": digest(data)}
    LOCK.write_text(json.dumps(record, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")
    check_lock()
    print(f"Synced {len(files)} upstream files at {version}; {len(generated)} generated integration files")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--source", type=Path)
    group.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        check_lock()
        print("PASS xrt snapshot hashes")
    else:
        refresh(args.source)


if __name__ == "__main__":
    main()
